### ISSUE TITLE
Client training using CPUs

### ISSUE THREAD

**Issue by neshkatrapati** [FedML-AI/FedLLM#3]
Is it possible to train LLAMA2 using 1000+ CPU-only clients using Fed-ML ?. Please help

**Comment by fedml-zijianhu** [comment]
It is possible but could be very slow. It also depends on the task and dataset.

For your specific question, do you mean **pretrain** or **fine-tune**?

For pretrain, it is impossible since Llama was pre-trained on 2048 Nvidia A100 for about a month. CPU-only machines are not fast enough.

**Comment by neshkatrapati** [comment]
My goal is to train a Language Model for a particular language (Telugu). Let's say I could fine tune LLAMA2 on the target language. Would that be possible using fedml ?

**Comment by fedml-zijianhu** [comment]
Yes. You can set `using_gpu: False` in the yaml config. Since you only have CPU-only machines, the training/fine-tuning speed is likely undesirably long. You can play around with the config to see the actual time estimate.

Notice that since you have more than 1000+ clients, your training will also likely be bottlenecked by network traffic.

**Comment by neshkatrapati** [comment]
Thank you ! Will seek your help again if required
